run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/whitedns/vless-tester
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
